version: '3.8'

services:

  api:

    build:
      context: .
      dockerfile: dockerfile

    ports:
      - '80'

    deploy:
      replicas: 4 
    
    restart: always

    environment:
      - PING_LISTEN_PORT=80
    
    

  proxy:

    image: nginx:latest

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80